export type SceneKey =
  | 'start'
  | 'part1'
  | 'part1SceneASuccess1'
  | 'part1SceneASuccess2'
  | 'part1SceneAFail1'
  | 'part1SceneAFail2'
  | 'part1SceneBMain'
  | 'part1SceneBSuccess'
  | 'part1SceneBFail1'
  | 'part1SceneBFail2'
  | 'part2'
  | 'part2SceneAMain'
  | 'part2SceneASuccess'
  | 'part2SceneAFail1'
  | 'part2SceneAFail2'
  | 'part3'
