export type SceneKey =
  | 'start'
  | 'part1'
  | 'part1SceneASuccess'
  | 'part1SceneAFail1'
  | 'part1SceneAFail2'
  | 'part2'
  | 'part2SceneB'
  | 'part2SceneBFail1'
  | 'part2SceneBFail2'
  | 'part2SceneC'
